/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    noticias: Noticia;
    recintos: Recinto;
    galerias: Galeria;
    videos: Video;
    paginas: Pagina;
    destacados: Destacado;
    'mensajes-contacto': MensajesContacto;
    redirecciones: Redireccione;
    forms: Form;
    'form-submissions': FormSubmission;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    noticias: NoticiasSelect<false> | NoticiasSelect<true>;
    recintos: RecintosSelect<false> | RecintosSelect<true>;
    galerias: GaleriasSelect<false> | GaleriasSelect<true>;
    videos: VideosSelect<false> | VideosSelect<true>;
    paginas: PaginasSelect<false> | PaginasSelect<true>;
    destacados: DestacadosSelect<false> | DestacadosSelect<true>;
    'mensajes-contacto': MensajesContactoSelect<false> | MensajesContactoSelect<true>;
    redirecciones: RedireccionesSelect<false> | RedireccionesSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    navegacion: Navegacion;
    'pie-de-pagina': PieDePagina;
    'ajustes-del-sitio': AjustesDelSitio;
    portada: Portada;
  };
  globalsSelect: {
    navegacion: NavegacionSelect<false> | NavegacionSelect<true>;
    'pie-de-pagina': PieDePaginaSelect<false> | PieDePaginaSelect<true>;
    'ajustes-del-sitio': AjustesDelSitioSelect<false> | AjustesDelSitioSelect<true>;
    portada: PortadaSelect<false> | PortadaSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Cuentas del personal de la Corporación que edita el portal.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  nombre: string;
  rol: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Fotografías del portal. El texto alternativo es obligatorio.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  /**
   * Describe la imagen para quien no puede verla. Obligatorio.
   */
  alt: string;
  /**
   * Miniatura borrosa generada sola al subir la imagen. No se edita a mano.
   */
  blurDataURL?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Noticias e informaciones para vecinas y vecinos de la comuna.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "noticias".
 */
export interface Noticia {
  id: string;
  titulo: string;
  /**
   * Se genera solo desde el título. Editable si necesitas una URL distinta.
   */
  slug: string;
  /**
   * Uno o dos renglones. Aparece bajo el título en las tarjetas.
   */
  bajada?: string | null;
  categoria: 'deportivo' | 'cultural' | 'artistico' | 'salud' | 'formativo' | 'comunitario';
  publicadaEn: string;
  portada?: (string | null) | Media;
  cuerpo: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Lo que se ve en el resultado de Google y en la vista previa al compartir en redes. Si se deja vacío, se arma solo desde el título, el resumen y la portada.
   */
  seo?: {
    metaTitulo?: string | null;
    /**
     * Hasta 160 caracteres. Es lo que Google muestra bajo el título.
     */
    metaDescripcion?: string | null;
    /**
     * Si se deja vacía, se usa la portada de la pieza.
     */
    imagenCompartir?: (string | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Estadio, gimnasio, piscinas y demás recintos que administra la Corporación.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "recintos".
 */
export interface Recinto {
  id: string;
  nombre: string;
  /**
   * Se genera solo desde el título. Editable si necesitas una URL distinta.
   */
  slug: string;
  /**
   * Si aún no está confirmada, escribe un marcador como «[dirección por confirmar]»: nunca una dirección inventada.
   */
  direccion: string;
  /**
   * Una por una. Ej: Fútbol, luego Atletismo.
   */
  disciplinas?: string[] | null;
  /**
   * Cantidad de personas.
   */
  aforo?: number | null;
  portada?: (string | null) | Media;
  /**
   * URL de la plataforma de trámites para arrendar este recinto. Déjalo vacío si no se arrienda.
   */
  urlReserva?: string | null;
  /**
   * Un ítem por cada día con horario distinto. Los días sin ítem se muestran cerrados.
   */
  horarios?:
    | {
        dia: '0' | '1' | '2' | '3' | '4' | '5' | '6';
        /**
         * Casi siempre un solo tramo. Dos si el recinto cierra al mediodía.
         */
        tramos: {
          inicio: string;
          fin: string;
          id?: string | null;
        }[];
        id?: string | null;
      }[]
    | null;
  /**
   * Lo que se ve en el resultado de Google y en la vista previa al compartir en redes. Si se deja vacío, se arma solo desde el título, el resumen y la portada.
   */
  seo?: {
    metaTitulo?: string | null;
    /**
     * Hasta 160 caracteres. Es lo que Google muestra bajo el título.
     */
    metaDescripcion?: string | null;
    /**
     * Si se deja vacía, se usa la portada de la pieza.
     */
    imagenCompartir?: (string | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Álbumes de fotos de actividades y campeonatos.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "galerias".
 */
export interface Galeria {
  id: string;
  titulo: string;
  /**
   * Se genera solo desde el título. Editable si necesitas una URL distinta.
   */
  slug: string;
  descripcion?: string | null;
  portada?: (string | null) | Media;
  imagenes: (string | Media)[];
  /**
   * Lo que se ve en el resultado de Google y en la vista previa al compartir en redes. Si se deja vacío, se arma solo desde el título, el resumen y la portada.
   */
  seo?: {
    metaTitulo?: string | null;
    /**
     * Hasta 160 caracteres. Es lo que Google muestra bajo el título.
     */
    metaDescripcion?: string | null;
    /**
     * Si se deja vacía, se usa la portada de la pieza.
     */
    imagenCompartir?: (string | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Videos de YouTube para incrustar en páginas y galerías.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videos".
 */
export interface Video {
  id: string;
  titulo: string;
  /**
   * La parte después de "v=" o "youtu.be/" en la URL del video. Ej: en youtu.be/aqz-KE-bpKQ, el ID es aqz-KE-bpKQ.
   */
  idYoutube: string;
  descripcion?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Páginas institucionales armadas con bloques: Quiénes somos, Historia, etc.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "paginas".
 */
export interface Pagina {
  id: string;
  titulo: string;
  /**
   * Se genera solo desde el título. Editable si necesitas una URL distinta.
   */
  slug: string;
  /**
   * Se usa en resultados de búsqueda internos y como respaldo del SEO.
   */
  resumen?: string | null;
  portada?: (string | null) | Media;
  contenido?:
    | (
        | BloqueTexto
        | BloqueImagen
        | BloqueGaleria
        | BloqueCita
        | BloquePreguntas
        | BloqueHorarios
        | BloqueLlamada
        | BloqueVideo
        | BloqueFormulario
        | BloqueSeparador
      )[]
    | null;
  /**
   * Lo que se ve en el resultado de Google y en la vista previa al compartir en redes. Si se deja vacío, se arma solo desde el título, el resumen y la portada.
   */
  seo?: {
    metaTitulo?: string | null;
    /**
     * Hasta 160 caracteres. Es lo que Google muestra bajo el título.
     */
    metaDescripcion?: string | null;
    /**
     * Si se deja vacía, se usa la portada de la pieza.
     */
    imagenCompartir?: (string | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BloqueTexto".
 */
export interface BloqueTexto {
  contenido: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'texto';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BloqueImagen".
 */
export interface BloqueImagen {
  imagen: string | Media;
  pie?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'imagen';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BloqueGaleria".
 */
export interface BloqueGaleria {
  titulo?: string | null;
  imagenes: (string | Media)[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'galeria';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BloqueCita".
 */
export interface BloqueCita {
  texto: string;
  autor?: string | null;
  /**
   * Ej: Dirección de la Corporación.
   */
  cargo?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cita';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BloquePreguntas".
 */
export interface BloquePreguntas {
  titulo?: string | null;
  items: {
    pregunta: string;
    respuesta: string;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'preguntas';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BloqueHorarios".
 */
export interface BloqueHorarios {
  titulo?: string | null;
  filas: {
    /**
     * Ej: Lunes a viernes.
     */
    dia: string;
    /**
     * Ej: 08:30 – 17:30.
     */
    horario: string;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'horarios';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BloqueLlamada".
 */
export interface BloqueLlamada {
  titulo: string;
  texto?: string | null;
  /**
   * Ruta interna (/talleres) o URL externa completa.
   */
  enlace: string;
  textoEnlace: string;
  externo?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'llamada';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BloqueVideo".
 */
export interface BloqueVideo {
  /**
   * Elige un video del catálogo. Si el que buscas no existe, créalo primero en Videos.
   */
  video: string | Video;
  id?: string | null;
  blockName?: string | null;
  blockType: 'video';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BloqueFormulario".
 */
export interface BloqueFormulario {
  /**
   * Elige un formulario creado en «Formularios». Si el que buscas no existe, créalo primero ahí.
   */
  formulario: string | Form;
  id?: string | null;
  blockName?: string | null;
  blockType: 'formulario';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: string;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'date';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    type?: ('reference' | 'custom') | null;
    reference?: {
      relationTo: 'paginas';
      value: string | Pagina;
    } | null;
    url?: string | null;
  };
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BloqueSeparador".
 */
export interface BloqueSeparador {
  id?: string | null;
  blockName?: string | null;
  blockType: 'separador';
}
/**
 * Hasta cinco piezas para el carrusel de la portada.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "destacados".
 */
export interface Destacado {
  id: string;
  titulo: string;
  bajada?: string | null;
  imagen: string | Media;
  /**
   * Ruta interna (/noticias/...) o URL externa completa.
   */
  enlace: string;
  textoEnlace?: string | null;
  externo?: boolean | null;
  /**
   * De menor a mayor. Dos piezas con el mismo número se ordenan por fecha.
   */
  orden: number;
  /**
   * Apagador rápido: desmarca para sacarlo ya mismo.
   */
  activo?: boolean | null;
  vigenciaDesde?: string | null;
  vigenciaHasta?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Mensajes enviados desde el formulario de contacto del portal.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mensajes-contacto".
 */
export interface MensajesContacto {
  id: string;
  nombre: string;
  correo: string;
  telefono?: string | null;
  asunto: string;
  mensaje: string;
  leido?: boolean | null;
  /**
   * Registrada al enviar, de solo lectura.
   */
  ip?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Cuando una URL cambie o se elimine una página, crea una entrada aquí para que el enlace viejo no se rompa.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirecciones".
 */
export interface Redireccione {
  id: string;
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'paginas';
          value: string | Pagina;
        } | null)
      | ({
          relationTo: 'noticias';
          value: string | Noticia;
        } | null)
      | ({
          relationTo: 'recintos';
          value: string | Recinto;
        } | null)
      | ({
          relationTo: 'galerias';
          value: string | Galeria;
        } | null);
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: string;
  form: string | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: string;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'noticias';
        value: string | Noticia;
      } | null)
    | ({
        relationTo: 'recintos';
        value: string | Recinto;
      } | null)
    | ({
        relationTo: 'galerias';
        value: string | Galeria;
      } | null)
    | ({
        relationTo: 'videos';
        value: string | Video;
      } | null)
    | ({
        relationTo: 'paginas';
        value: string | Pagina;
      } | null)
    | ({
        relationTo: 'destacados';
        value: string | Destacado;
      } | null)
    | ({
        relationTo: 'mensajes-contacto';
        value: string | MensajesContacto;
      } | null)
    | ({
        relationTo: 'redirecciones';
        value: string | Redireccione;
      } | null)
    | ({
        relationTo: 'forms';
        value: string | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: string | FormSubmission;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  nombre?: T;
  rol?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  blurDataURL?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "noticias_select".
 */
export interface NoticiasSelect<T extends boolean = true> {
  titulo?: T;
  slug?: T;
  bajada?: T;
  categoria?: T;
  publicadaEn?: T;
  portada?: T;
  cuerpo?: T;
  seo?:
    | T
    | {
        metaTitulo?: T;
        metaDescripcion?: T;
        imagenCompartir?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "recintos_select".
 */
export interface RecintosSelect<T extends boolean = true> {
  nombre?: T;
  slug?: T;
  direccion?: T;
  disciplinas?: T;
  aforo?: T;
  portada?: T;
  urlReserva?: T;
  horarios?:
    | T
    | {
        dia?: T;
        tramos?:
          | T
          | {
              inicio?: T;
              fin?: T;
              id?: T;
            };
        id?: T;
      };
  seo?:
    | T
    | {
        metaTitulo?: T;
        metaDescripcion?: T;
        imagenCompartir?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "galerias_select".
 */
export interface GaleriasSelect<T extends boolean = true> {
  titulo?: T;
  slug?: T;
  descripcion?: T;
  portada?: T;
  imagenes?: T;
  seo?:
    | T
    | {
        metaTitulo?: T;
        metaDescripcion?: T;
        imagenCompartir?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videos_select".
 */
export interface VideosSelect<T extends boolean = true> {
  titulo?: T;
  idYoutube?: T;
  descripcion?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "paginas_select".
 */
export interface PaginasSelect<T extends boolean = true> {
  titulo?: T;
  slug?: T;
  resumen?: T;
  portada?: T;
  contenido?:
    | T
    | {
        texto?: T | BloqueTextoSelect<T>;
        imagen?: T | BloqueImagenSelect<T>;
        galeria?: T | BloqueGaleriaSelect<T>;
        cita?: T | BloqueCitaSelect<T>;
        preguntas?: T | BloquePreguntasSelect<T>;
        horarios?: T | BloqueHorariosSelect<T>;
        llamada?: T | BloqueLlamadaSelect<T>;
        video?: T | BloqueVideoSelect<T>;
        formulario?: T | BloqueFormularioSelect<T>;
        separador?: T | BloqueSeparadorSelect<T>;
      };
  seo?:
    | T
    | {
        metaTitulo?: T;
        metaDescripcion?: T;
        imagenCompartir?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BloqueTexto_select".
 */
export interface BloqueTextoSelect<T extends boolean = true> {
  contenido?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BloqueImagen_select".
 */
export interface BloqueImagenSelect<T extends boolean = true> {
  imagen?: T;
  pie?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BloqueGaleria_select".
 */
export interface BloqueGaleriaSelect<T extends boolean = true> {
  titulo?: T;
  imagenes?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BloqueCita_select".
 */
export interface BloqueCitaSelect<T extends boolean = true> {
  texto?: T;
  autor?: T;
  cargo?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BloquePreguntas_select".
 */
export interface BloquePreguntasSelect<T extends boolean = true> {
  titulo?: T;
  items?:
    | T
    | {
        pregunta?: T;
        respuesta?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BloqueHorarios_select".
 */
export interface BloqueHorariosSelect<T extends boolean = true> {
  titulo?: T;
  filas?:
    | T
    | {
        dia?: T;
        horario?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BloqueLlamada_select".
 */
export interface BloqueLlamadaSelect<T extends boolean = true> {
  titulo?: T;
  texto?: T;
  enlace?: T;
  textoEnlace?: T;
  externo?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BloqueVideo_select".
 */
export interface BloqueVideoSelect<T extends boolean = true> {
  video?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BloqueFormulario_select".
 */
export interface BloqueFormularioSelect<T extends boolean = true> {
  formulario?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BloqueSeparador_select".
 */
export interface BloqueSeparadorSelect<T extends boolean = true> {
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "destacados_select".
 */
export interface DestacadosSelect<T extends boolean = true> {
  titulo?: T;
  bajada?: T;
  imagen?: T;
  enlace?: T;
  textoEnlace?: T;
  externo?: T;
  orden?: T;
  activo?: T;
  vigenciaDesde?: T;
  vigenciaHasta?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mensajes-contacto_select".
 */
export interface MensajesContactoSelect<T extends boolean = true> {
  nombre?: T;
  correo?: T;
  telefono?: T;
  asunto?: T;
  mensaje?: T;
  leido?: T;
  ip?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirecciones_select".
 */
export interface RedireccionesSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        date?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navegacion".
 */
export interface Navegacion {
  id: string;
  /**
   * El orden aquí es el orden en la cabecera.
   */
  items?:
    | {
        etiqueta: string;
        /**
         * Ruta interna que empieza con / (ej: /noticias) o URL externa completa.
         */
        href: string;
        /**
         * Márcalo si el enlace lleva fuera del portal: se abre en otra pestaña y avisa con un icono.
         */
        externo?: boolean | null;
        /**
         * Si agregas sub-ítems, el ítem pasa a ser un desplegable y su propio enlace queda como primera opción dentro («Ver …»).
         */
        hijos?:
          | {
              etiqueta: string;
              /**
               * Ruta interna que empieza con / (ej: /noticias) o URL externa completa.
               */
              href: string;
              /**
               * Márcalo si el enlace lleva fuera del portal: se abre en otra pestaña y avisa con un icono.
               */
              externo?: boolean | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * La franja delgada que va sobre el logo, con los enlaces legales y los íconos de redes sociales. Las redes se cargan en «Ajustes del sitio».
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pie-de-pagina".
 */
export interface PieDePagina {
  id: string;
  /**
   * Transparencia, Ley del Lobby, Privacidad. Si apuntan al portal del municipio y no a una página de este sitio, marca «Sale del portal».
   */
  enlacesLegales?:
    | {
        etiqueta: string;
        /**
         * Ruta interna que empieza con / (ej: /noticias) o URL externa completa.
         */
        href: string;
        /**
         * Márcalo si el enlace lleva fuera del portal: se abre en otra pestaña y avisa con un icono.
         */
        externo?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Identidad y contacto. Los datos de contacto se ven en el pie de página; los íconos de redes, en la barra superior.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ajustes-del-sitio".
 */
export interface AjustesDelSitio {
  id: string;
  nombreCorporacion: string;
  /**
   * Se ve en el pie de página. Si aún no está confirmada, usa un marcador evidente, nunca una inventada.
   */
  direccion: string;
  /**
   * Se ve en el pie de página.
   */
  telefono: string;
  /**
   * Se ve en el pie de página. Texto libre y no un campo de correo validado a propósito: mientras no esté confirmado, aquí va un marcador como «[correo por confirmar]», que un campo de tipo email rechazaría por no tener forma de dirección.
   */
  correo: string;
  /**
   * Los íconos se ven en la barra superior, arriba del logo. Solo aparece la red que tenga URL cargada: dejar una en blanco la oculta.
   */
  redes?: {
    facebook?: string | null;
    instagram?: string | null;
    youtube?: string | null;
    tiktok?: string | null;
    x?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Los accesos rápidos y los títulos de sección de la página de inicio. El carrusel se edita en «Destacados»; las noticias y los recintos se llenan solos.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portada".
 */
export interface Portada {
  id: string;
  /**
   * La fila de cuatro tarjetas bajo el carrusel. Con menos de cuatro la fila se acomoda sola; si dejas la lista vacía, se muestran los cuatro de siempre.
   */
  accesos?:
    | {
        titulo: string;
        /**
         * Una línea. La tarjeta es chica y un párrafo no cabe.
         */
        descripcion?: string | null;
        /**
         * Ruta interna que empieza con / (ej: /recintos) o URL externa completa.
         */
        href: string;
        /**
         * Márcalo si lleva a la plataforma de trámites o a otro sitio: se abre en otra pestaña y la tarjeta lo avisa.
         */
        externo?: boolean | null;
        /**
         * El dibujo del cuadrito de arriba de la tarjeta.
         */
        icono: 'balon' | 'ubicacion' | 'calendario' | 'telefono' | 'correo' | 'reloj' | 'imagen' | 'info' | 'buscar';
        id?: string | null;
      }[]
    | null;
  tituloNoticias?: string | null;
  tituloRecintos?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navegacion_select".
 */
export interface NavegacionSelect<T extends boolean = true> {
  items?:
    | T
    | {
        etiqueta?: T;
        href?: T;
        externo?: T;
        hijos?:
          | T
          | {
              etiqueta?: T;
              href?: T;
              externo?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pie-de-pagina_select".
 */
export interface PieDePaginaSelect<T extends boolean = true> {
  enlacesLegales?:
    | T
    | {
        etiqueta?: T;
        href?: T;
        externo?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ajustes-del-sitio_select".
 */
export interface AjustesDelSitioSelect<T extends boolean = true> {
  nombreCorporacion?: T;
  direccion?: T;
  telefono?: T;
  correo?: T;
  redes?:
    | T
    | {
        facebook?: T;
        instagram?: T;
        youtube?: T;
        tiktok?: T;
        x?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portada_select".
 */
export interface PortadaSelect<T extends boolean = true> {
  accesos?:
    | T
    | {
        titulo?: T;
        descripcion?: T;
        href?: T;
        externo?: T;
        icono?: T;
        id?: T;
      };
  tituloNoticias?: T;
  tituloRecintos?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'noticias';
          value: string | Noticia;
        } | null)
      | ({
          relationTo: 'recintos';
          value: string | Recinto;
        } | null)
      | ({
          relationTo: 'galerias';
          value: string | Galeria;
        } | null)
      | ({
          relationTo: 'paginas';
          value: string | Pagina;
        } | null);
    global?: string | null;
    user?: (string | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}